version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env.api
    environment:
      PORT: 8081
      JDBC_URL: "jdbc:postgresql://dpg-d35mk7mmcj7s73a1v3p0-a.oregon-postgres.render.com:5432/rideshare_0f0c?sslmode=require"
      JDBC_USER: "rideshare_0f0c_user"
      JDBC_PASSWORD: "pVA8dV96Rz99cPnItSYDPdU4SqKRjY55"
      DB_URL: "jdbc:postgresql://dpg-d35mk7mmcj7s73a1v3p0-a.oregon-postgres.render.com:5432/rideshare_0f0c?sslmode=require"
      DB_USER: "rideshare_0f0c_user"
      DB_PASS: "pVA8dV96Rz99cPnItSYDPdU4SqKRjY55"
      TZ: Australia/Melbourne
      JAVA_TOOL_OPTIONS: -Duser.timezone=Australia/Melbourne
      APP_TZ: Australia/Melbourne

    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
